[package]
name = "discord_news"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2"
serenity = "0.11"
tokio = { version= "1", features = ["full"] }
chrono = "0.4.24"
serde_json = "1.0"